credentials:
  usernames:
    Wyndham:
      email: wyndham@council.com
      name: Wyndham Council
      password: $2b$12$zTX4H8CmQZqJVLs6lNUpwOeSHQKL8bTxvE8tL2S1aACZPVRO2Vj9S  # "llama"
cookie:
  name: policysimplify_auth
  key: some_secret_key
  expiry_days: 3
preauthorized:
  emails:
    - testuser@council.com
